version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.10.113
      # Configure the advertised hostname automatically
      # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Automatically create topics
      # PokoyaTopic will have 3 partition and 2 replicas
      KAFKA_CREATE_TOPICS: "PokoyaTopic:3:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
